preprocess: True
train: True
generate: True
experiment_id: 03
#destination_dir: "data_preprocessed/fairseq_preprocessed"
#data_directory: ""
features_requested: ["dependency", "frequency", "length", "levenshtein"]
language: en  # or de
arch: "transformer"
optimizer: "adam"
batch_size: 12
test_batch_size: 12
max_epochs: 50
beam_size: 8
lr: 0.00011
